language: node_js

node_js:
  - "8"
  - "9"
  - "stable"

install:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - onejar99@gmail.com
    on_success: always
    on_failure: always
